import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CreateAccountScreen extends JFrame {
    /**
     * Initializing GUI elements
     * GUI layout is handled by IntelliJ UI Designer. See $$$setupUI$$$() below.
     */
    public JPanel createAccountPanel;
    private JLabel accountCreationLabel, firstNameLabel, lastNameLabel, phoneNumLabel, emailLabel, addressLabel, cityLabel, stateLabel, zipLabel, passLabel, confirmPassLabel, errorLabel;
    private JTextField firstNameTextField, lastNameTextField, phoneNumTextField, emailTextField, addressTextField, cityTextField, stateTextField, zipTextField;
    private JPasswordField passwordField, confirmPasswordField;
    private JButton createAccountButton, returnToLoginScreenButton;

    /**
     * Initializes a CreateAccountScreen and handles ActionListeners for createAccountButton and returnToLoginScreenButton
     *
     * @param title
     */
    public CreateAccountScreen(String title) {
        super(title);

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(createAccountPanel);
        this.setSize(800, 600);
        this.pack();

        createAccountButton.addActionListener(new ActionListener() {
            /**
             * Creates a new account using Customer.createAccount().
             * @param e
             * @throws Exception when the two password fields do not match or a field is left blank
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    String fn = firstNameTextField.getText();
                    String ln = lastNameTextField.getText();
                    String pn = phoneNumTextField.getText();
                    String email = emailTextField.getText();
                    String sa = addressTextField.getText();
                    String c = cityTextField.getText();
                    String s = stateTextField.getText();
                    String z = zipTextField.getText();
                    String pw = passwordField.getText();
                    String cpw = confirmPasswordField.getText();

                    JTextField[] allFields = {firstNameTextField, lastNameTextField, phoneNumTextField, emailTextField, addressTextField, cityTextField, stateTextField, zipTextField, passwordField, confirmPasswordField};
                    for (JTextField field : allFields) {
                        if (field.getText().equals("")) {
                            throw new Exception("Please fill in all fields.");
                        }
                    }

                    if (!pw.equals(cpw)) {
                        throw new Exception("Passwords do not match.");
                    }

                    Customer.createAccount(fn, ln, pn, email, sa, c, s, z, pw);
                    errorLabel.setForeground(Color.GREEN);
                    errorLabel.setText("Account successfully created!");

                } catch (Exception ex) {
                    errorLabel.setForeground(Color.RED);
                    errorLabel.setText(ex.getMessage());
                    ex.printStackTrace();
                }

            }
        });

        returnToLoginScreenButton.addActionListener(new ActionListener() {
            /**
             * Closes current window and opens new LoginScreen
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                JFrame frame = new LoginScreen(title);
                frame.setVisible(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createAccountPanel = new JPanel();
        createAccountPanel.setLayout(new GridLayoutManager(14, 2, new Insets(10, 10, 10, 10), -1, -1));
        accountCreationLabel = new JLabel();
        accountCreationLabel.setText("Mom and Pop's Pizzeria: Account Registration");
        createAccountPanel.add(accountCreationLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        firstNameLabel = new JLabel();
        firstNameLabel.setText("First Name");
        createAccountPanel.add(firstNameLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        firstNameTextField = new JTextField();
        createAccountPanel.add(firstNameTextField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lastNameLabel = new JLabel();
        lastNameLabel.setText("Last Name");
        createAccountPanel.add(lastNameLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        phoneNumLabel = new JLabel();
        phoneNumLabel.setText("Phone Number");
        createAccountPanel.add(phoneNumLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        emailLabel = new JLabel();
        emailLabel.setText("Email Address");
        createAccountPanel.add(emailLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addressLabel = new JLabel();
        addressLabel.setText("Street Address");
        createAccountPanel.add(addressLabel, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cityLabel = new JLabel();
        cityLabel.setText("City");
        createAccountPanel.add(cityLabel, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stateLabel = new JLabel();
        stateLabel.setText("State");
        createAccountPanel.add(stateLabel, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zipLabel = new JLabel();
        zipLabel.setText("ZIP");
        createAccountPanel.add(zipLabel, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lastNameTextField = new JTextField();
        createAccountPanel.add(lastNameTextField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        phoneNumTextField = new JTextField();
        createAccountPanel.add(phoneNumTextField, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        emailTextField = new JTextField();
        createAccountPanel.add(emailTextField, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        addressTextField = new JTextField();
        createAccountPanel.add(addressTextField, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cityTextField = new JTextField();
        createAccountPanel.add(cityTextField, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        stateTextField = new JTextField();
        createAccountPanel.add(stateTextField, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        zipTextField = new JTextField();
        createAccountPanel.add(zipTextField, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passLabel = new JLabel();
        passLabel.setText("Password");
        createAccountPanel.add(passLabel, new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        confirmPassLabel = new JLabel();
        confirmPassLabel.setText("Confirm Password");
        createAccountPanel.add(confirmPassLabel, new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField = new JPasswordField();
        createAccountPanel.add(passwordField, new GridConstraints(10, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        confirmPasswordField = new JPasswordField();
        createAccountPanel.add(confirmPasswordField, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        createAccountButton = new JButton();
        createAccountButton.setText("Create Account");
        createAccountPanel.add(createAccountButton, new GridConstraints(12, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        returnToLoginScreenButton = new JButton();
        returnToLoginScreenButton.setText("Return to Login Screen");
        createAccountPanel.add(returnToLoginScreenButton, new GridConstraints(13, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorLabel = new JLabel();
        errorLabel.setForeground(new Color(-65536));
        errorLabel.setText("");
        createAccountPanel.add(errorLabel, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return createAccountPanel;
    }

}
